#!/usr/bin/env bash
# Displays a phrase indefinitely and catches SIGTERM signals
# Ensure there are no extra spaces or characters before the trap

trap "echo 'I am invincible!!!'" SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done

