#!/usr/bin/env bash
# Checks for the existence, emptiness, and type of the file named school
if [ -e school ]; then
    echo "school file exists"

    # Further checks if the file exists
    if [ -s school ]; then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi

    # Check if it is a regular file
    if [ -f school ]; then
        echo "school is a regular file"
    fi

else
    echo "school file does not exist"
fi
